[[onnxruntime_cpu]]
arch = "x86_64"
git-tree-sha1 = "ee0b3b47cb5c295d8e2df9b704d472fa827fbb59"
lazy = true
os = "windows"

    [[onnxruntime_cpu.download]]
    sha256 = "f132ee57ab970c496f08e344bef60f03d3cf61475c93628feef2a1ac94e88aa1"
    url = "https://github.com/jw3126/ONNXRunTimeArtifacts/releases/download/v1.15.1-rc1/onnxruntime-win-x64-1.15.1.tgz"
[[onnxruntime_cpu]]
arch = "x86_64"
git-tree-sha1 = "fe904e447d592a9cf7aaac236a58a94f91f761d1"
lazy = true
libc = "glibc"
os = "linux"

    [[onnxruntime_cpu.download]]
    sha256 = "5492f9065f87538a286fb04c8542e9ff7950abb2ea6f8c24993a940006787d87"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.15.1/onnxruntime-linux-x64-1.15.1.tgz"
[[onnxruntime_cpu]]
arch = "x86_64"
git-tree-sha1 = "fcb94c1a37609b80bf69b143bfcd60b0ff1fbef1"
lazy = true
os = "macos"

    [[onnxruntime_cpu.download]]
    sha256 = "ecb7651c216fe6ffaf4c578e135d98341bc5bc944c5dc6b725ef85b0d7747be0"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.15.1/onnxruntime-osx-universal2-1.15.1.tgz"
[[onnxruntime_cpu]]
arch = "aarch64"
git-tree-sha1 = "fcb94c1a37609b80bf69b143bfcd60b0ff1fbef1"
lazy = true
os = "macos"

    [[onnxruntime_cpu.download]]
    sha256 = "ecb7651c216fe6ffaf4c578e135d98341bc5bc944c5dc6b725ef85b0d7747be0"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.15.1/onnxruntime-osx-universal2-1.15.1.tgz"

[[onnxruntime_gpu]]
arch = "x86_64"
git-tree-sha1 = "68acc458450c6cff16f55c8cedba213f1eeeb678"
lazy = true
os = "windows"

    [[onnxruntime_gpu.download]]
    sha256 = "94aea5b7ec2ffeecca8225816116922cab7ce0f4f2a5516c28e241cdbf4c04db"
    url = "https://github.com/jw3126/ONNXRunTimeArtifacts/releases/download/v1.15.1-rc1/onnxruntime-win-x64-gpu-1.15.1.tgz"
[[onnxruntime_gpu]]
arch = "x86_64"
git-tree-sha1 = "d7e3cdf6598724d24e8f854817c6e71a1f6fe57e"
lazy = true
libc = "glibc"
os = "linux"

    [[onnxruntime_gpu.download]]
    sha256 = "eab891393025edd5818d1aa26a42860e5739fcc49e3ca3f876110ec8736fe7f1"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.15.1/onnxruntime-linux-x64-gpu-1.15.1.tgz"
